name: CI # название скрипта: будет отображаться во вкладке Actions

on: [push] # действие, по которому запускается данный скрипт

jobs: # роботы, которые будут выполняться
  build: # сборка, которая..
    runs-on: ubuntu-latest # ..будет запущена на основе этого образа

    steps: # шаги которые будут проделаны после запуска образа
      - name: Checout
      - uses: actions/checkout@v1 # переход в самую актуальную ветку
      - name: Install node
        uses: actions/setup-node@v1
        with:
          node-wersion: "16.13.1"
      - run: yarn install
      - run: yarn build
      - name: Deploy
      - uses: crazy-max/ghaction-github-pages
        with:
          target_branch: gh-pages
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
